### PR TITLE
#258 Android Intents rule support

### PR DESCRIPTION
**Pull request by guyacosta**
#258

### CODE REVIEW

**Comment by guyacosta** [comment]
Java, C++, C# support added and tested

**Comment by guyacosta** [comment]
See #261 with split out enhancement request for device permissions detection and #262 for Kotlin language support request.  This PR covers existing supported languages and Intents only.

**Comment by scovetta** [comment]
I think we should add the specific intents instead of just usage of intents -- meaning things like ACTION_SET_ALARM. Might need to separate those out into the relevant category instead of bucketing them into a general intent tag.

**Comment by gfs** [comment]
Agree with Mike, all Android apps will use Intents in some way. What is interesting is what Intents they ask for.  I imagine many map directly to existing tags.

**Pull request merged**
