### PR TITLE
Use System.Text.Json instead of Newton.Json

### LINKED ISSUE #515: Refactor to use System.Text.Json
**Is your feature request related to a problem? Please describe.**
App inspector deserializes using Newtonsoft.Json, accordingly it ignores System.Text.Json attributes. If you were to extend an AI rule with more attributes and then call AddString, even if you the `T` is specified the deserialization may not be correct if your json properties dont match the attribute names or if they have special handling.

Any downstream users who implement extensions to AI (like DevSkim) are then required to include newtonsoft for the annotations to use the `AddString` methods.

**Describe the solution you'd like**
Ideally AppInspector could just use System.Text.Json for serialization in the rules path, using the standard attributes.

### PR DESCRIPTION
**Pull request by dbalikhin**
Fixes #515

### CODE REVIEW

**Comment by dbalikhin** [comment]
@microsoft-github-policy-service agree

**Comment by gfs** [comment]
Thanks for your contribution.  This is an excellent improvement I think.

I added a simple benchmark to test the speed of just the export time. It generates a trivial report with N issues for setup and then exports the same report to JSON repeatedly. The benchmark shows about a 2x speedup, and about 10x less memory allocations.

Current main branch
|                Method |     N |      Mean |     Error |    StdDev | Ratio |     Gen0 |  Allocated | Alloc Ratio |
|---------------------- |------ |----------:|----------:|----------:|------:|---------:|-----------:|------------:|
| ExportRecordsToJson |  1000 |  3.680 ms | 0.0736 ms | 0.1833 ms |  1.00 |  23.4375 |  387.88 KB |        1.00 |
|                       |       |           |           |           |       |          |            |             |
| ExportRecordsToJson | 10000 | 30.532 ms | 0.6079 ms | 1.5138 ms |  1.00 | 218.7500 | 3762.89 KB |        1.00 |

This PR
|                Method |     N |      Mean |     Error |    StdDev | Ratio |    Gen0 | Allocated | Alloc Ratio |
|---------------------- |------ |----------:|----------:|----------:|------:|--------:|----------:|------------:|
| ExportRecordsToJson |  1000 |  2.052 ms | 0.0494 ms | 0.1442 ms |  1.00 |       - |  52.17 KB |        1.00 |
|                       |       |           |           |           |       |         |           |             |
| ExportRecordsToJson | 10000 | 13.035 ms | 0.2579 ms | 0.4310 ms |  1.00 | 15.6250 |  480.6 KB |        1.00 |

**Review by gfs — APPROVED** [review]

**Comment by gfs** [comment]
This is relatively large in terms of files touched so I'm going to give it another look tomorrow to double check nothing got missed but I expect to merge it sometime tomorrow.

**Review by daalcant — APPROVED** [review]

**Comment by dbalikhin** [comment]
Thanks folks, I really appreciate your responsiveness. I will check this PR if I need to modify anything.

**Comment by gfs** [comment]
@dbalikhin I did a quick check of the json, sarif and html outputs compared to the latest release from main and everything looks good, as well as double checking that custom rules can still be specified and loaded properly.

Thanks again for the contribution, great work!

**Comment by dbalikhin** [comment]
@gfs 
>Thanks again for the contribution, great work!

My pleasure.

**Pull request merged**
